# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Black-Fu' do

pod 'Alamofire', '~> 3.0'
pod 'SDWebImage'
pod 'NVActivityIndicatorView'

end

target 'Black-FuTests' do

end

target 'Black-FuUITests' do

end

target 'Fast-Search' do

end

